### ISSUE TITLE
方法不能有返回值？

### ISSUE THREAD

**Issue by andarly** [yoojia/NextEvents#1]
为什么注册的方法不可以有返回值

**Comment by yoojia** [comment]
你的问题不清晰。我猜想你想问的可能是：”@Subscribe 注解的方法为什么必须是void返回值？“。这个问题是，@Subscribe 注解的方法，它的作用是收到事件消息后被触发执行。这个过程是单向的，如果它有返回值，那这个返回值会被丢弃。因此，在框架扫描时，会强制检查返回值必须为void。
